### ISSUE TITLE
Project Support Request: DevOps workers limits being hit

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/projects#29]
Azure DevOps agents pools are having some wait times before starting their jobs at the moment. 

![image](https://user-images.githubusercontent.com/5834289/69236942-b0844c80-0be8-11ea-8098-3961efadb812.png)

This issue is shared by any projects that are using the common Azure DevOps shared amongst .NET Foundation projects.

This is mostly affecting the VS2017 work pool.

**Comment by onovotny** [comment]
Have you seen this consistently? There may be some fluctuation with the pool itself. There still aren't great ways of seeing total average queue times, but looking at when agents were active, it looks like the top-most haven't been hit in a while:

![image](https://user-images.githubusercontent.com/1427284/69251966-3ddf8680-0b80-11ea-85fe-14f97fd2d487.png)

**Comment by glennawatson** [comment]
I tend to use this screen: https://dev.azure.com/dotnet/ReactiveUI/_settings/agentqueues?queueId=188&view=jobs

I look at the Wait Queue time. I am seeing consistent times when the wait queue time goes up throughout the day, then it has some idle time overnight.

**Comment by onovotny** [comment]
I think we should keep an eye on it for now and I can raise it with the Pipelines team as well. For the most part, I see quick pickup by the agents. I don't deep queues on the higher agents, so it's possible there was an underlying hiccup.

**Comment by glennawatson** [comment]
Sounds good. I will keep an eye on it for the next week and will either
close/comment back here.

**Comment by glennawatson** [comment]
The issue is happening at the moment with the wait time increasing on the devops, I am getting this error message at the moment `There are no agents that satisfy the job’s demands
There is a problem with deploy job 'Agent phase'. No agent pool was found with ID 34.`

**Comment by glennawatson** [comment]
```
##[Error 1]
Exception Message: The pipeline is not valid. Could not find a pool with ID 34. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)
Exception Stack Trace: at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidatePipelineProcess(IVssRequestContext requestContext, Guid scopeIdentifier, Int32 definitionId, Guid planId, PipelineEnvironment environment, PipelineProcess pipeline, BuildOptions options) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6212
at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidateProcess(IVssRequestContext requestContext, Guid scopeIdentifier, TaskOrchestrationOwner definition, Guid planId, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions options) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6133
at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.CreatePlan(IVssRequestContext requestContext, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 349
at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.RunPlan(IVssRequestContext requestContext, TaskAgentPoolReference pool, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 1505
at Microsoft.VisualStudio.Services.ReleaseManagement.Server.DistributedTask.PipelineOrchestrator.StartDeployment(AutomationEngineInput input) in D:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\DistributedTask\PipelineOrchestrator.cs:line 77
at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in D:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 222 
```

**Comment by jongalloway** [comment]
@glennawatson Can we close this? It looks like wait times are averaging 1-2 seconds lately, with a high of 4 seconds.

**Comment by glennawatson** [comment]
Yeah haven't seen the issue since.
